//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by M3DText.rc
//
#define IDI_ICON1                       101
#define IDB_CUT                         113
#define IDR_MMLOBJPAINTADDSCHEME        166
#define IDR_MMLTEXTURESEL               168
#define IDR_PHOTOLETCHWORTH             172
#define IDR_PAINTINGMITCH               173
#define IDR_EAGLEEYE                    245
#define IDR_LOGO                        300
#define IDR_MMLTEXTURELIBRARY           359
#define IDR_MMLTEXTURERENAME            360
#define IDR_MMLTEXTURENEW               361
#define IDR_MMLTEXTUREWOODPLANKS        362
#define IDR_MMLTEXTUREDIRTPAINT         363
#define IDR_MMLTEXTUREGENERATEPLANK     364
#define IDR_MMLTEXTUREGENERATETREE      365
#define IDR_MMLTEXTURENOISE             366
#define IDR_MMLTEXTURECRNOISE           367
#define IDR_MMLTEXTURECORR              368
#define IDR_MMLTEXTURETILES             369
#define IDR_MMLTEXTUREMAKETILE          370
#define IDR_MMLTEXTURECHIP              371
#define IDR_MMLTEXTUREGROUT             372
#define IDR_MMLTEXTUREBMP               373
#define IDR_MMLTEXTUREIMAGEFILE         374
#define IDR_MMLTEXTUREPARQUET           376
#define IDR_MMLTEXTUREMAKESTONE         377
#define IDR_MMLTEXTURESTONES            378
#define IDR_MMLTEXTURESTONESRANDOM      379
#define IDR_MMLTEXTUREPAVERS            380
#define IDR_MMLTEXTUREMARBLING          381
#define IDR_MMLTEXTUREMARBLE            382
#define IDR_MMLTEXTURECLAPBOARDS        383
#define IDR_MMLTEXTUREBOARDBATTEN       384
#define IDR_MMLTEXTURESHINGLES          385
#define IDR_MMLTEXTURELATTICE           386
#define IDR_MMLTEXTUREWICKER            387
#define IDR_MMLTEXTURETHREADS           389
#define IDR_MMLTEXTUREFABRIC            390
#define IDR_MMLTEXTURESTRIPES           391
#define IDR_PAINTINGKITE                392
#define IDR_PAINTINGPUGGLE              393
#define IDR_PAINTINGQUOLL               394
#define IDR_PHOTOKAKADU                 395
#define IDR_PHOTOMINDIL                 396
#define IDR_PHOTOPAYASO                 397
#define IDR_PHOTOULURU                  398
#define IDR_MMLMACROS                   500
#define IDR_MMLTEMPLATEBACK             501
#define IDR_PHOTOMOON                   578
#define IDR_LEAFACACIA                  644
#define IDR_LEAFUMBRELLA                645
#define IDR_LEAFSANDPALM                646
#define IDR_LEAFKAPOCK                  647
#define IDR_LEAFKAKADUPLUM              648
#define IDR_LEAFIRONWOOD                649
#define IDR_LEAFGRASS                   650
#define IDR_LEAFEUCALYPT                651
#define IDR_MML1                        802
#define IDR_MMLTEXTFROMFILE             802
#define IDR_MMLTEXTBLANK                803
#define IDR_MML2                        804
#define IDR_MMLTEXTURETESTPATTERN       804
#define IDR_MMLVOLWOOD                  806
#define IDR_MMLVOLMARBLE                807
#define IDR_MMLVOLNOISE                 808
#define IDR_MMLVOLSANDSTONE             809
#define IDR_MMLTEXTUREIRIS              810
#define IDR_MMLTEXTUREBLOODVESSELS      811
#define IDR_MML3                        812
#define IDR_MMLTEXTUREHAIR              812
#define IDR_MMLTEXTUREGRASS             813
#define IDR_MML4                        814
#define IDR_MMLTEXTUREBRANCH            814
#define IDR_MMLTEXTUREFACEOMATIC        815
#define IDR_MMLTEXTUREFACEOMATICBASE    816
#define IDR_MMLTEXTUREFACEOMATICOILY    817
#define IDR_MMLTEXTUREFACEOMATICMAKEUP  818
#define IDR_MMLTEXTUREFACEOMATICWARTS   819
#define IDR_MMLTEXTUREFACEOMATICSCARS   820
#define IDR_MMLTEXTUREFACEOMATICFUR     821
#define IDR_FACEWRINKLESLIPS2           822
#define IDR_FACEACNE1                   823
#define IDR_FACEBEARD1                  824
#define IDR_FACEBEARD2                  825
#define IDR_FACEBEARDSHADOW1            826
#define IDR_FACEEYEBROWS1               827
#define IDR_FACEEYEBROWS2               828
#define IDR_FACEEYEBROWS3               829
#define IDR_FACEEYELINER1               830
#define IDR_FACEEYELINER2               831
#define IDR_FACEEYESHADOW1              832
#define IDR_FACEFACE1                   833
#define IDR_FACEFACE2                   834
#define IDR_FACEFACE3                   835
#define IDR_FACEFACE4                   836
#define IDR_FACEFRECKLES                837
#define IDR_FACELIPSTICK1               838
#define IDR_FACEOILYSKIN                839
#define IDR_FACEROUGE1                  840
#define IDR_FACESCAREYES1               841
#define IDR_FACESCAREYES2               842
#define IDR_FACESCARMOUTH1              843
#define IDR_FACETATOO1                  844
#define IDR_FACETATOO2                  845
#define IDR_FACETATOO3                  846
#define IDR_FACEWRINKLESEYES1           847
#define IDR_FACEWRINKLESEYES2           848
#define IDR_FACEWRINKLESLIPS1           849
#define IDR_MML5                        850
#define IDR_MMLTEXTURECHAINMAIL         850
#define IDR_MMLTEXTURETREEBARK          851
#define IDR_MMLTEXTUREMIX               852
#define IDR_MMLTEXTURETEXT              853
#define IDR_MML6                        854
#define IDR_MMLTEXTUREEFFECTTEXT        854
#define IDR_MMLLEAFFORTEXTURE           855
#define IDR_GRASSMISSION                856
#define IDR_LEAFMAPLE                   857
#define IDR_LEAFOAK                     858
#define IDR_FLOWERKAPOCK                859
#define IDR_POSSUMFURLENGTH             860
#define IDR_POSSUMEARS                  861
#define IDR_POSSUMFURCOLOR1             862
#define IDR_POSSUMFURCOLOR2             863
#define IDR_POSSUMFURCOLOR3             864
#define IDR_POSSUMFURCOLOR4             865
#define IDR_POSSUMFURCOLOR5             866
#define IDR_POSSUMFURCOLOR6             867
#define IDR_POSSUMSKIN                  868
#define IDR_ROOSKINCOLOR3               869
#define IDR_ROOEARS1                    870
#define IDR_ROOEARS2                    871
#define IDR_ROOEARS3                    872
#define IDR_ROOEARS4                    873
#define IDR_ROOFURCOLOR1                874
#define IDR_ROOFURCOLOR2                875
#define IDR_ROOFURCOLOR3                876
#define IDR_ROOFURCOLOR4                877
#define IDR_ROOFURCOLOR5                878
#define IDR_ROOFURCOLOR6                879
#define IDR_ROOFURCOLOR7                880
#define IDR_ROOFURCOLOR8                881
#define IDR_ROOFURCOLOR9                882
#define IDR_ROOFURCOLOR10               883
#define IDR_ROOFURLENGTH                884
#define IDR_ROOSKINCOLOR1               885
#define IDR_ROOSKINCOLOR2               886
#define IDR_RATSKINCOLOR2               887
#define IDR_RATFURCOLOR1                888
#define IDR_RATFURCOLOR2                889
#define IDR_RATFURCOLOR3                890
#define IDR_RATFURCOLOR4                891
#define IDR_RATFURCOLOR5                892
#define IDR_RATFURCOLOR6                893
#define IDR_RATFURLENGTH                894
#define IDR_RATSKINCOLOR1               895
#define IDR_JPG1                        896
#define IDR_THYLACINEFURCOLOR1          896
#define IDR_THYLACINEFURCOLOR2          897
#define IDR_THYLACINEFURCOLOR3          898
#define IDR_THYLACINEFURCOLOR4          899
#define IDR_THYLACINEFURCOLOR5          900
#define IDR_THYLACINEFURCOLOR6          901
#define IDR_THYLACINEFURLENGTH1         902
#define IDR_THYLACINESKINCOLOR1         903
#define IDR_THYLACINESKINCOLOR2         904
#define IDR_MMLTEXUTRELEAFLITTER        905
#define IDR_MMLTEXTURELEAFLITTER        905

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        906
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           801
#endif
#endif
