//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by M3DWaveDll.rc
//
#define IDI_ICON1                       101
#define IDI_APPICON                     101
#define IDB_PRINTER                     103
#define IDB_SAVE                        108
#define IDB_SAVEAS                      109
#define IDB_NEW                         110
#define IDB_OPEN                        111
#define IDB_HELP                        112
#define IDB_CUT                         113
#define IDB_COPY                        114
#define IDB_PASTE                       115
#define IDB_UNDO                        116
#define IDB_REDO                        117
#define IDB_DELETE                      118
#define IDB_DIALOGBOX                   126
#define IDB_SELREGION                   154
#define IDB_SELALL                      155
#define IDC_CURSORPASTE                 164
#define IDB_SELNONE                     169
#define IDC_CURSORZOOMIN                170
#define IDC_CURSORSELREGION             195
#define IDB_ZOOMIN                      225
#define IDR_MMLMACROS                   500
#define IDR_MMLTEMPLATEBACK             501
#define IDR_MMLTEMPLATEHELP             502
#define IDB_ANIMPLAY                    554
#define IDB_ANIMSTOP                    555
#define IDB_ANIMPLAYLOOP                556
#define IDB_ANIMJUMPSTART               557
#define IDB_ANIMJUMPEND                 558
#define IDB_BRUSHSHAPE                  574
#define IDB_BRUSHSTRENGTH               575
#define IDB_BRUSHEFFECT                 576
#define IDB_BRUSH32                     578
#define IDB_BRUSH16                     579
#define IDB_BRUSH8                      580
#define IDB_BRUSH4                      581
#define IDB_BRUSH64                     582
#define IDB_ANIMRECORD                  583
#define IDB_SHOWWAVE                    584
#define IDB_SHOWFFT                     585
#define IDB_PASTEMIX                    586
#define IDB_FX                          587
#define IDB_ZOOMALL                     588
#define IDB_SELPLAYBACK                 589
#define IDB_SHOWOTHERS                  590
#define IDB_ANIMPLAYSEL                 591
#define IDB_ZOOMSEL                     592
#define IDB_SHOWPHONEMES                593
#define IDB_NEWPHONE                    594
#define IDB_SPEECHRECOG                 595
#define IDB_SHOWMOUTH                   596
#define IDB_NEWWORD                     597
#define IDC_CURSORBRUSH32               612
#define IDC_CURSORBRUSH16               613
#define IDC_CURSORBRUSH8                614
#define IDC_CURSORBRUSH4                615
#define IDC_CURSORBRUSH64               616
#define IDR_MMLRECORD                   702
#define IDR_MMLSETTINGS                 703
#define IDR_MENUSHOWOTHERS              704
#define ID_SHOWOTHERS_ENERGY            705
#define IDR_MENUFX                      706
#define ID_FX_VOLUME                    707
#define ID_VOLUME_INCREASE              708
#define ID_VOLUME_DECREASE              709
#define ID_VOLUME_MAKESILENT            710
#define ID_VOLUME_NORMALIZE             711
#define ID_VOLUME_FADEIN                712
#define ID_VOLUME_FADEOUT               713
#define ID_VOLUME_INVERTSIGN            714
#define ID_FX_STRANGE                   715
#define ID_STRANGE_REVERSE              716
#define ID_FX_FILTERING                 717
#define ID_FILTERING_REMOVEDCOFFSET     718
#define ID_FX_STEREOEFFECTS             719
#define ID_STEREOEFFECTS_SWAPCHANNELS   720
#define ID_FX_SILENCE                   721
#define ID_SILENCE_NOISEREDUCTION       722
#define ID_FILTERING_BASSBOOST          723
#define ID_FILTERING_BASSREDUCE         724
#define ID_FILTERING_TREBLEBOOST        725
#define ID_FILTERING_TREBLEREDUCE       726
#define ID_FILTERING_OLD                727
#define ID_FILTERING_CHEAPRADIO         728
#define ID_SILENCE_TRIMSILENCEFROMSTARTANDEND 729
#define ID_STRANGE_REMOVEPHASE          730
#define ID_STRANGE_SWAPPHASE            731
#define ID_STRANGE_COMBTHROUGHFREQUENCIES 732
#define ID_STRANGE_INVERTFREQUENCIES    733
#define ID_STRANGE_STRETCHFREQUENCIES   734
#define ID_STRANGE_SHRINKFREQUENCIES    735
#define ID_STRANGE_COMBTHROUGHFREQUENCIES2 736
#define ID_FILTERING_REMOVESUB          737
#define IDR_MMLFXVolume                 738
#define ID_VOLUME_ADVANCEDVOLUME        739
#define IDR_MMLFXFILTER                 741
#define ID_FILTERING_ADVANCEDFILTERING  742
#define ID_FX_MISC                      743
#define ID_MISC_BLENDFORLOOP            744
#define IDR_MMLFXBLEND                  745
#define IDR_MMLFXACCOMPRESS             746
#define ID_MISC_ACOUSTICCOMPRESSION     747
#define IDR_MMLFXECHO                   748
#define ID_MISC_ECHOANDREVERB           749
#define IDR_MMLFXPITCHSPEED             750
#define ID_FX_PITCHANDSPEED             751
#define ID_PITCHANDSPEED_PICHANDSPEED   752
#define IDR_MMLFXSINE                   753
#define ID_MISC_GENERATESINEWAVE        754
#define ID_SHOWOTHERS_SPECTROGRAMOFSPECTROGRAM 755
#define ID_SHOWOTHERS_WAVEFORM          756
#define ID_SHOWOTHERS_SPECTROGRAM       757
#define ID_SHOWOTHERS_PITCH             758
#define IDR_MMLFXSPEED                  759
#define ID_PITCHANDSPEED_SPEEDWITHOUTPITCHSHIFT 760
#define IDR_MMLFXPITCH                  761
#define ID_PITCHANDSPEED_PITCHCHANGEWITHOUTSPEEDCHANGE 762
#define ID_SHOWOTHERS_SPECTROGRAMNOPITCH 763
#define ID_SHOWOTHERS_PHONEMES          764
#define ID_SHOWOTHERS_SPECTROGRAMOCTAVES 765
#define IDR_MMLSPEECHRECOG              766
#define ID_SHOWOTHERS_SPEECHRECOGNITIONPHONEMESCORES 767
#define ID_SHOWOTHERS_SPECTROGRAMSRFEAT 768
#define ID_SHOWOTHERS_MOUTH             769
#define IDR_MML1                        770
#define IDR_MMLHELP                     770
#define ID_SHOWOTHERS_SPECTROGRAMSRFEATVOICED 771
#define ID_SHOWOTHERS_SPECTROGRAMSRFEATNOISE 772
#define ID_FX_RESYNTHESIS               773
#define ID_RESYNTHESIS_CHANGETHEVOICE   774
#define ID_SHOWOTHERS_SPEECHRECOGNITIONFEATPHASE 775
#define IDR_MMLVOICESYNSETTINGS         776
#define ID_VOICEMODIFICATION_WHISPER    777
#define ID_SHOWOTHERS_WORDS             778
#define IDR_MMLWORDRENAME               779
#define IDR_MMLWAVEOPEN                 781
#define IDB_FOLDER                      782
#define IDR_MMLLEXPRONOOV               783
#define IDR_MMLLEXLANGID                784
#define IDR_MMLLEXMAIN                  785
#define IDR_MMLLEXPHONE                 786
#define IDR_MMLLEXPRONEDIT              787
#define IDR_MMLLEXPRONMAIN              788
#define IDR_MMLSRMAIN                   789
#define IDR_MMLTTSMAIN                  790
#define IDR_MMLRECREVIEW                791
#define IDR_MMLTTSREVIEW                792
#define IDR_MMLFXTTS                    793
#define ID_FX_TEXT                      794
#define ID_TEXT_TEXT                    795
#define IDR_MMLLEXPRONREVIEW            796
#define IDR_MMLLEXPOSREVIEW             797
#define IDR_MMLLEXGRAMMAR               798
#define IDR_MMLLEXLTS                   799
#define IDR_MMLTRANSPROS1               800
#define IDR_MMLTRANSPROS2               801
#define ID_TEXT_TRANSPLANTEDPROSODY     802
#define IDR_MMLTTSMODIFIEDMAIN          803
#define IDR_MMLTTSMODIFIEDPRON          804
#define IDR_MML2                        805
#define IDR_MMLTTSMODIFIEDPROS          805
#define IDR_MML3                        806
#define IDR_MMLVDSTARTWIZARD            807
#define ID_VOICEMODIFICATION_VOICEDISGUISETESTBUGBUG 808
#define IDR_MMLVDTYPESOFMICS            809
#define IDR_MMLTESTMIC                  810
#define IDR_MMLVDNOSOUNDCARD            811
#define IDB_BITMAPSCOPEQUIET            812
#define IDB_BITMAPSCOPECLIP             813
#define IDB_BITMAPSCOPEFLAT             814
#define IDB_BITMAPSCOPEGOOD             815
#define IDR_MMLVDRECORDNEXT             816
#define IDR_MMLVDRECORDSAMPLEPLAYBACK   817
#define IDR_MMLVDSTARTDISGUISE          818
#define IDR_MMLVDLOADMIMICAUDIO         819
#define IDR_MMLVDENTERTRANSCRIPTION     820
#define IDR_MMLVDRECORDORIG             821
#define IDR_MMLVDCLEARSETTINGSNOT       822
#define IDR_MMLVDCLEARSETTINGS          823
#define IDR_MMLVDADJUSTPITCH            824
#define IDR_MMLVDMOVEMARKERS            825
#define IDR_MMLVDOCTAVESTRETCHES        826
#define IDR_MMLVDFINETUNEPHONEME        827
#define IDR_MMLVDPHONEMEDATABASE        828
#define IDR_MMLVDEXTRASETTINGS          829
#define IDR_MMLVDSAVE                   830
#define IDR_MMLVDNOOFFENSIVE            831
#define IDR_MMLVDVOICECHATTUTORIAL      832
#define IDR_MMLTTSMODIFIEDSUBVOICE      833
#define IDR_MMLWAVEDIRINFOADDFILES      834
#define ID_VOICEMODIFICATION_VOICECHATBUGBUG 835
#define ID_VOICEMODIFICATION_VOICECHATBUGBUG836 836
#define IDR_MML4                        837
#define IDR_MMLTTSMAINADDMANY           837
#define IDR_MMLVDSTARTDISGUISEMIMIC     838
#define IDR_MMLVDSTARTDISGUISEQUICK     839
#define IDR_MMLVDRECORDORIGQUICK        840
#define IDR_MMLQUICKOPTIONS             841
#define IDR_MMLLEXGRAMMARGROUP          842
#define IDR_MMLLEXGRAMMARRULE           843
#define ID_VOICEMODIFICATION_VOICECHAT  844
#define IDR_MMLFXTTSBATCH               845
#define ID_TEXT_BATCHTEXT               846
#define IDR_MMLFXMONOTONE               847
#define IDR_MMLTRANSPROSQUICK2          848
#define IDR_MMLTRANSPROSQUICK1          849
#define IDR_MML5                        850
#define IDR_MMLTTSMODIFIEDIMPORT        850
#define IDR_MML6                        851
#define IDR_MMLLEXIMPORTUNISYN          851
#define IDR_MML7                        852
#define IDR_MMLLEXIMPORTMANDARIN        852
#define IDR_MML8                        853
#define IDR_MMLLEXIMPORTMANDARIN2       853
#define IDR_MMLFXPSOLA                  854
#define IDR_MMLTTSMAINSIMPLE            855
#define IDR_MML9                        856
#define IDR_MMLTTSREVIEWSIMPLE          856
#define ID_VOICEMODIFICATION_MONOTONE   40001
#define ID_SHOWOTHERS_SPEECHRECOGNITIONFEATURES 40002
#define ID_SHOWOTHERS_SPEECHRECOGNITIONFEATURES40003 40003
#define ID_SHOWOTHERS_SPEECHRECOGNITIONFEATPHASEPITCH 40004
#define ID_VOICEMODIFICATION_PSOLAPITCH 40005
#define ID_SILENCE_NOISEREDUCTIONSTRONG 40006

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        857
#define _APS_NEXT_COMMAND_VALUE         40007
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
