//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by M3DView.rc
//
#define IDI_ICON1                       101
#define IDI_APPICON                     101
#define IDB_PRINTER                     103
#define IDB_CLOSE                       104
#define IDB_MINIMIZE                    105
#define IDB_NEXTMONITOR                 106
#define IDB_CLONEVIEW                   107
#define IDB_SAVE                        108
#define IDB_SAVEAS                      109
#define IDB_NEW                         110
#define IDB_OPEN                        111
#define IDB_HELP                        112
#define IDB_CUT                         113
#define IDB_COPY                        114
#define IDB_PASTE                       115
#define IDB_UNDO                        116
#define IDB_REDO                        117
#define IDB_DELETE                      118
#define IDB_VIEWFLAT                    120
#define IDB_VIEW3D                      121
#define IDB_VIEWWALKTHROUGH             122
#define IDI_LIGHTDISABLED               123
#define IDI_LIGHTBLUE                   124
#define IDI_ARROWDISABLED               125
#define IDI_ARROWRED                    126
#define IDB_DIALOGBOX                   126
#define IDB_VIEWFLATLRUD                127
#define IDB_VIEWFLATSCALE               128
#define IDB_VIEWFLATROTZ                129
#define IDB_VIEWFLATROTX                130
#define IDB_VIEW3DLRFB                  131
#define IDB_VIEW3DROTY                  132
#define IDB_VIEWWALKFBROTZ              133
#define IDB_VIEWWALKROTZX               134
#define IDB_VIEWWALKROTY                135
#define IDB_VIEWWALKLRUD                136
#define IDR_MMLVIEWSET                  136
#define IDB_VIEWWALKLRFB                137
#define IDR_MMLVIEWSETCOLOR             137
#define IDB_VIEWSETCENTER               138
#define IDR_MMLVIEWSETLIGHTING          139
#define IDR_MMLVIEWSETMEASUREMENT       140
#define IDR_MMLVIEWSETPERSPECTIVE       142
#define IDR_MMLVIEWSETSOLID             144
#define IDR_MMLVIEWSETSPEED             145
#define IDR_MMLVIEWFLAT                 146
#define IDR_MMLVIEW3D                   147
#define IDR_MMLVIEWWALK                 148
#define IDB_VIEWFLATLOOKAT              149
#define IDB_CLIPLINE                    150
#define IDR_MMLCLIPPOINT                150
#define IDB_CLIPPOINT                   151
#define IDR_MMLCLIPSET                  151
#define IDB_CLIPSET                     152
#define IDR_MMLCLIPSETHAND              152
#define IDR_MMLCLIPSETFLOORS            153
#define IDB_SELINDIVIDUAL               153
#define IDR_MMLVIEWSETGRID              154
#define IDB_SELREGION                   154
#define IDB_SELALL                      155
#define IDR_MMLSELECT                   155
#define IDR_MMLSELECTCOLOR              156
#define IDB_MOVELRUD                    156
#define IDB_MOVEUD                      156
#define IDR_MMLSELECTREGION             157
#define IDB_MOVEREFERENCE               157
#define IDB_MOVELRFB                    158
#define IDR_MMLMOVESET                  158
#define IDB_MOVENSEW                    158
#define IDB_MOVEROTZ                    159
#define IDR_MMLMOVELOC                  159
#define IDB_MOVEROTX                    160
#define IDR_MMLMOVEORIENT               160
#define IDB_MOVEROTY                    161
#define IDR_MMLMOVELOCGRID              161
#define IDR_MMLMOVEORIENTGRID           162
#define IDB_OBJCONTROL                  162
#define IDB_OBJCONTROLNSEW              162
#define IDB_OBJPAINT                    163
#define IDC_CURSORPASTE                 164
#define IDB_OBJNEW                      164
#define IDC_CURSORPAINT                 165
#define IDR_MMLOBJPAINT                 165
#define IDB_OBJCHOOSEMAJOR              165
#define IDC_CURSOROBJECTPASTE           166
#define IDB_OBJDIALOG                   166
#define IDR_MMLOBJPAINTHELP             167
#define IDC_CURSORDIALOG                167
#define IDB_VIEWFLATQUICK               167
#define IDB_OBJINTELADJUST              168
#define IDC_CURSORINTELADJUST           168
#define IDB_SELNONE                     169
#define IDC_CURSORDECONSTRUCT           169
#define IDB_OBJDECONSTRUCT              170
#define IDC_CURSORZOOMIN                170
#define IDB_CLIPLEVEL                   171
#define IDC_CURSORZOOMINDRAG            171
#define IDC_CURSORZOOMOUT               172
#define IDC_CURSOROBJOPENCLOSE          173
#define IDC_CURSOROBJONOFF              174
#define IDC_CURSORGRIDFROMPOINT         175
#define IDC_CURSORVIEWFLATLRUD          176
#define IDC_CURSORVIEW3DLRFB            177
#define IDC_CURSORVIEWWALKFBROTZ        178
#define IDC_CURSORVIEWWALKROTZX         179
#define IDC_CURSORVIEWWALKLRUD          180
#define IDR_MMLOBJCONTROLPOINTMOVE      181
#define IDC_CURSORVIEWWALKLRFB          181
#define IDR_MMLOBJSETTINGS              182
#define IDC_CURSORMOVENSEW              182
#define IDC_CURSORMOVEEMBED             183
#define IDR_MENUQUICK                   184
#define IDC_CURSORMOVEUD                184
#define IDC_CURSORVIEWFLATSCALE         185
#define IDC_CURSORVIEWFLATROTZ          186
#define IDC_CURSORVIEWWALKROTY          187
#define IDC_CURSORMOVEROTZ              188
#define IDC_CURSORVIEWFLATROTX          189
#define IDC_CURSORVIEW3DROTY            190
#define IDC_CURSORMOVEROTX              191
#define IDC_CURSORMOVEROTY              192
#define IDC_CURSORVIEWFLATLOOKAT        193
#define IDC_CURSORCLIPLINE              194
#define IDR_MMLGROUNDWATER              195
#define IDC_CURSORSELREGION             195
#define IDR_MMLGROUNDDISPLAY            196
#define IDC_CURSORVIEWCENTERFLAT        196
#define IDR_MMLGROUNDSIZE               197
#define IDC_CURSORCLIPPOINT             197
#define IDC_CURSOROBJCONTROLNSEW        198
#define IDR_MMLGROUNDBOUNDARY           199
#define IDC_CURSOROBJECTPASTEDRAG       199
#define IDR_MMLGROUNDBOUNDARY2          200
#define IDC_CURSORZOOMAT                200
#define IDC_CURSOROBJCONTROLDIALOG      201
#define IDC_CURSORTHUMBNAIL             202
#define IDC_CURSOROBJCONTROLNSEWUD      203
#define IDC_CURSOROBJCONTROLUD          204
#define IDC_CURSORMOVENSEWUD            205
#define IDC_CURSOROBJCONTROLINOUT       206
#define IDC_CURSOROBJMERGE              207
#define IDC_CURSOROBJATTRIB             208
#define IDC_CURSOROBJATTACH             209
#define IDC_CURSORANIMMOVELR            210
#define IDR_MENULEVEL                   219
#define IDR_MMLCLIPLEVELS               220
#define IDR_MMLCLIPSHOW                 221
#define IDB_LOCALE                      222
#define IDR_MMLLOCALESET                223
#define IDB_VIEWQUALITY                 223
#define IDR_MMLLOCALETIME               224
#define IDB_SMALLWINDOW                 224
#define IDR_MMLLOCALEINFO               225
#define IDB_ZOOMIN                      225
#define IDR_MENUQUALITY                 226
#define IDB_ZOOMINDRAG                  226
#define IDR_MMLQUALITY                  227
#define IDB_ZOOMOUT                     227
#define IDB_OBJONOFF                    228
#define IDR_MMLGRIDSET                  228
#define IDB_OBJOPENCLOSE                229
#define IDR_MMLGRIDVALUES               229
#define IDB_GRIDSELECT                  230
#define IDR_MMLGRIDFROMPOINT            230
#define IDB_GRIDFROMPOINT               231
#define IDB_OBJCONTROLUD                232
#define IDR_MMLLOCALELEVELS             232
#define IDB_MOVEEMBED                   233
#define IDR_SPLASH                      234
#define IDB_LIBRARY                     234
#define IDB_ZOOMAT                      235
#define IDR_HMAIN                       236
#define IDB_OBJCONTROLDIALOG            236
#define IDR_HSEARCH                     237
#define IDB_THUMBNAIL                   237
#define IDR_HABOUT                      238
#define IDB_OBJCONTROLNSEWUD            238
#define IDR_HTOC                        239
#define IDB_MOVENSEWUD                  239
#define IDR_HTUTORIALSTART              240
#define IDB_OBJEDITOR                   240
#define IDR_HBUGS                       241
#define IDB_OBJMERGE                    241
#define IDR_HHISTORY                    242
#define IDB_TRACING                     242
#define IDR_HSYSTEM                     243
#define IDB_OBJCONTROLINOUT             243
#define IDR_HPRODCOMAPRE                244
#define IDB_OBJECTLIST                  244
#define IDR_EAGLEEYE                    245
#define IDR_HTUTORIALBUILDSITE          246
#define IDR_HTUTORIALBUTTONS            247
#define IDR_HVIEWSMALL                  248
#define IDR_HVIEWSCREEN                 249
#define IDR_HVIEWMULTIPLE               250
#define IDR_HTUTORIALBUILDBLOCK1        251
#define IDR_HGROUDNWATER                252
#define IDR_HGROUNDCOUNTOUR             253
#define IDR_HGROUNDSIZE                 254
#define IDR_HLOCALE                     256
#define IDR_HTUTORIALVIEWS              257
#define IDR_HTUTORIALBUILDBLOCK2        258
#define IDR_HVIEWROTATING               259
#define IDR_HVIEWGLASSES                260
#define IDR_HVIEWLIGHTING               261
#define IDR_HVIEWOUTLINES               262
#define IDR_HVIEWPERSPECTIVE            263
#define IDR_HVIEWQUALITY                264
#define IDR_HFOG                        265
#define IDR_HTUTORIALBUILDBLOCK3        266
#define IDR_HBBWALLS                    267
#define IDR_HBBELEVLIMIT                268
#define IDR_HBBFOUNDATION               269
#define IDR_HBBLEVELS                   270
#define IDR_HBBROOF                     271
#define IDR_HBBVERANDAH                 272
#define IDR_HBBCATHEDRAL                273
#define IDR_HTUTORIALCLIP               274
#define IDR_HOBJREFERENCE               275
#define IDR_HTUTORIALBUILDBLOCK4        276
#define IDR_HTUTORIALBUILDBLOCK5        277
#define IDR_HBBBYPASS                   278
#define IDR_HBBDECONSTRUCT              279
#define IDR_HTUTORIALSAVE               280
#define IDR_HTUTORIALTEXTURES           281
#define IDR_HTUTORIALWALLS              282
#define IDR_HBBOVERLAYS                 283
#define IDR_HTUTORIALDOORS              284
#define IDR_HGRIDSIZE                   285
#define IDR_HGRIDDISPLAY                286
#define IDR_HGRIDCENTER                 287
#define IDR_HTUTORIALFINISHED           288
#define IDR_HTIPVR                      289
#define IDR_HTIPBUILDER                 290
#define IDR_HTIPLANDLORD                291
#define IDR_HTIPLANDSCAPE               292
#define IDR_HTIPPEOPLEBUILD             293
#define IDR_HTIPPEOPLELANDSCAPE         294
#define IDR_HTIPRPG                     295
#define IDR_HTIPARCHITECT               296
#define IDR_HFUTURE                     297
#define IDR_HIFYOULIKE                  299
#define IDR_LOGO                        300
#define IDR_HTUTORIALWALLS2             301
#define IDR_HSURFACETHICK               302
#define IDR_HSURFACEEDGE                303
#define IDR_HSURFACEOVERLAY             304
#define IDR_HSURFACECURVE               305
#define IDR_HBALINBB                    334
#define IDR_HDOORSCUSTOM                337
#define IDR_HSTAIRSCUSTOM               338
#define IDR_HSTAIRSOBJECT               339
#define IDR_HPIERCUSTOM                 340
#define IDR_HPIEROBJECT                 341
#define IDR_HPIERINBB                   342
#define IDR_HBALCUSTOM                  343
#define IDR_HBALOBJECT                  344
#define IDR_HBALINSTAIRS                345
#define IDR_HFENCING                    346
#define IDR_HDOORSSIZE                  347
#define IDR_HDOORSOPEN                  348
#define IDR_HTUTORIALOUTSIDE            349
#define IDR_HTUTORIALFINISHEDVIEW       350
#define IDR_HTUTORIALOPENSAMPLE         351
#define IDR_HTUTORIALVIEWS2             352
#define IDR_HTUTORIALIMAGEQUALITY       353
#define IDR_HTUTORIALVIEWS3             354
#define IDR_HTUTORIALVIEWS4             355
#define IDR_MMLVIEWFAVORITE             356
#define IDR_MENULIBRARY                 358
#define IDR_HLIGHTONOFF                 399
#define IDR_HLIGHTCUSTOM                400
#define IDR_HLIGHTCREATE                401
#define IDR_HLIGHTSUN                   402
#define IDR_HVIEWEXPOSURE               403
#define IDR_HTEXTURECREATE              404
#define IDR_HTEXTUREMODIFY              405
#define IDR_HTEXTUREMATERIAL            406
#define IDR_HTUTORIALINSIDE             407
#define IDR_MENUTHUMBNAIL               409
#define IDR_HTHUMBNAIL                  410
#define IDR_MMLOBJEDITOR                415
#define IDR_HTUTORIALOBJSTART           416
#define IDR_HTUTORIALOBJTHEORY          417
#define IDR_HTUTORIALOBJCREATE          418
#define IDR_HTUTORIALOBJEDIT            419
#define IDR_HTUTORIALOBJEDIT2           420
#define IDR_HTUTORIALOBJSAVE            421
#define IDR_HTUTORIALFINISHED3          422
#define IDR_HTUTORIALOBJTEMPLATE        426
#define IDR_HEXTRUSION                  427
#define IDR_HLATHE                      431
#define IDR_HCOLUMN                     432
#define IDR_HSPLINESURFACE              437
#define IDR_HPOLYHEDRON                 439
#define IDR_HPAINTING                   444
#define IDR_HTABLECLOTH                 446
#define IDR_HCURTAIN                    448
#define IDR_HCUSHION                    450
#define IDR_HBOOKS                      452
#define IDR_HCABINET                    454
#define IDR_HCABINETPIECES              455
#define IDR_HDRAWER                     457
#define IDR_HPATHWAY                    459
#define IDR_HTARP                       460
#define IDR_HPOOL                       462
#define IDR_HFIREPLACE                  463
#define IDR_HTRUSS                      465
#define IDR_HTBBATH                     466
#define IDR_HTBKITCHEN                  467
#define IDR_HSURFACEMERGE               468
#define IDR_HBBMERGE                    469
#define IDR_MMLAPPSET                   470
#define IDR_HSURFACEFRAMING             472
#define IDR_HTBEXPOSEDEAVES             473
#define IDR_MENUPRINT                   474
#define ID_PRINT_PRINT                  475
#define ID_PRINT_SAVEIMAGE              476
#define IDR_MMLPRINTTOFILE              477
#define IDR_MMLPRINTTOPRINTER           479
#define IDR_HSAVEIMAGE                  480
#define IDR_HPRINT                      481
#define IDR_MMLTRACEDIALOG              482
#define IDR_MMLTRACEADD                 483
#define IDR_MMLTRACEEDIT                484
#define IDR_HTRACE                      485
#define IDR_MMLREGISTER                 486
#define IDR_HRIGHTBUTTON                489
#define IDB_ARROWRIGHT                  490
#define IDB_ARROWDOWN                   491
#define IDR_MENUOLOBJECT                491
#define IDB_ARROWNONE                   492
#define ID_OLOBJECT_SELECTORDE          492
#define ID_OLOBJECT_SHOW                493
#define IDB_OBJATTRIB                   493
#define ID_OLOBJECT_MOVETOANEWGROUP     494
#define IDB_ARROWUP                     494
#define ID_OLOBJECT_RENAME              495
#define IDB_OBJATTACH                   495
#define ID_OLOBJECT_REPOSITIONCAMERATOVIEWTHIS 496
#define IDB_ANIM                        496
#define ID_OLOBJECT_MOVETOANEXISTINGGROUP 497
#define IDB_NEWANIMKEYFRAME             497
#define ID_OLOBJECT_MOVEOUTOFTHISGROUP  498
#define IDB_ANIMMOVELR                  499
#define IDR_MMLMACROS                   500
#define IDB_ANIMMOVEUD                  500
#define IDR_MMLTEMPLATEBACK             501
#define IDB_NEWANIMPATH                 501
#define IDR_MMLTEMPLATEHELP             502
#define IDB_ANIMRESIZE                  502
#define IDR_MMLOLNEWGROUP               503
#define IDR_MMLOLRENAMEOBJECT           505
#define IDR_MENUOLGROUP                 506
#define ID_GROUP_SELECT                 507
#define ID_GROUP_SHOW                   508
#define ID_GROUP_MOVETOANEXISTINGGROUP  509
#define ID_GROUP_MOVEALLOBJECTSOUTOFTHISGROUP 510
#define ID_GROUP_MOVETOANEWGROUP        511
#define ID_GROUP_RENAMEGROUP            512
#define ID_GROUP_REPOSITIONCAMERATOVIEWTHIS 513
#define IDR_MML1                        514
#define IDR_MMLOBJATTRIB                514
#define IDR_MMLOBJEDITORSET             515
#define IDR_MMLOBJEDITORATTRIB          516
#define IDR_MMLOBJEDITORATTRIBSEL       517
#define IDR_MMLOBJEDITORATTRIBEDIT      518
#define IDR_MML2                        519
#define IDR_HTUTORIALBONE8              519
#define IDR_HOBJECTLIST                 523
#define IDR_HATTRIBUTES                 524
#define IDR_HTUTORIALOBJATTRIB          525
#define IDR_HPRODCOMPARE2               526
#define IDR_HBONESFACEFORWARDS          533
#define IDR_HBONESMOVEREF               534
#define IDR_HBONESRIGID                 535
#define IDR_HBONESCONVETIONS            536
#define IDR_HATTACH                     537
#define IDR_HHOWCHARACTERHOLD           538
#define IDR_MENUANIM                    539
#define ID_ANIMATION_SHOWTIMELINE       540
#define ID_ANIMATION_CREATEMOVIE        541
#define IDI_ICON2                       542
#define IDI_ANIMICON                    542
#define IDC_CURSORANIMMOVEUD            544
#define IDC_CURSORANIMRESIZER           545
#define IDC_CURSORANIMRESIZEL           546
#define IDI_BAYICON1                    547
#define IDC_CURSOROBJCONTROLNSEW1       547
#define IDB_NEWANIMKEYFRAMELOC          548
#define IDC_CURSORGRAPHPOINTMOVE        548
#define IDI_GROUNDICON                  548
#define IDB_NEWANIMKEYFRAMEROT          549
#define IDC_CURSORGRAPHPOINTDELETE      549
#define IDB_GRAPHPOINTMOVE              550
#define IDC_CURSORANIMTIME              550
#define IDB_GRAPHPOINTDELETE            551
#define IDC_CURSORANIMDEFAULT           551
#define IDB_SCENEFPS                    552
#define IDC_CURSORGROUNDSUN             552
#define IDB_SCENEBAYS                   553
#define IDB_ANIMPLAY                    554
#define IDR_HTUTORIALCONTENTS           554
#define IDB_ANIMSTOP                    555
#define IDR_HTUTORIALANIM1              555
#define IDB_ANIMPLAYLOOP                556
#define IDR_HTUTORIALANIM2              556
#define IDB_ANIMJUMPSTART               557
#define IDR_HTUTORIALANIM3              557
#define IDB_ANIMJUMPEND                 558
#define IDR_HTUTORIALANIM4              558
#define IDB_ANIMJUMPNEXT                559
#define IDR_HTUTORIALANIM5              559
#define IDB_ANIMJUMPPREV                560
#define IDR_HTUTORIALANIM6              560
#define IDB_SCENEMENU                   561
#define IDR_HTUTORIALANIM7              561
#define IDB_ANIMTIMEINSERT              562
#define IDR_HTUTORIALANIM8              562
#define IDB_ANIMTIMEREMOVE              563
#define IDR_HTUTORIALANIM9              563
#define IDB_ANIMDEFAULT                 564
#define IDR_HANIMBOOKMARK               564
#define IDB_ANIMSELACTIVE               565
#define IDR_HANIMDECONSTRUCT            565
#define IDB_NEWANIMBOOKMARK1            566
#define IDR_HANIMMERGE                  566
#define IDB_NEWANIMBOOKMARK2            567
#define IDR_HANIMSELCHANGE              567
#define IDB_SCENEBOOKMARK               568
#define IDR_HANIMSCENES                 568
#define IDB_SCENECAMERA                 569
#define IDR_HANIMFRAMERATE              569
#define IDB_ANIM1                       570
#define IDB_NEWANIMCAMERA               570
#define IDR_HANIMSTARTATTRIB            570
#define IDR_HANIMRESIZE                 571
#define IDB_GRIDTOPO                    571
#define IDB_GROUNDSUN                   572
#define IDB_GROUNDGENMTN                573
#define IDB_BRUSHSHAPE                  574
#define IDB_BRUSHSTRENGTH               575
#define IDB_BRUSHEFFECT                 576
#define ID_LIGHTINGEXPOSURE_DAYTIMEINTERIOR 577
#define IDB_BRUSH32                     578
#define IDB_BRUSH16                     579
#define IDB_BRUSH8                      580
#define IDR_HSKYDOME                    581
#define IDB_BRUSH4                      581
#define IDR_MENUBRUSHSHAPE              582
#define IDB_BRUSH64                     582
#define ID_BRUSHSHAPE_AIRBRUSH          583
#define IDB_GROUNDWATER                 583
#define ID_BRUSHSHAPE_BRUSH             584
#define IDB_GROUNDGENVOLCANO            584
#define ID_BRUSHSHAPE_PEN               585
#define IDB_GROUNDGENHILL               585
#define ID_BRUSHSHAPE_FLAT              586
#define IDB_GROUNDGENHILLROLL           586
#define ID_BRUSHSHAPE_ROUNDED           587
#define IDB_GROUNDGENPLAT               587
#define ID_BRUSHSHAPE_POINTY            588
#define IDB_GROUNDGENRAVINE             588
#define ID_BRUSHSHAPE_VERYPOINTY        589
#define IDB_GROUNDGENCRATER             589
#define IDR_MENUBRUSHSTRENGTH           590
#define IDB_GROUNDGENRAISE              590
#define ID_BRUSHSTRENGTH_10             591
#define IDB_GROUNDGENLOWER              591
#define ID_BRUSHSTRENGTH_9              592
#define IDB_GROUNDGENFLAT               592
#define ID_BRUSHSTRENGTH_8              593
#define IDB_GROUNDAPPLYWIND             593
#define ID_BRUSHSTRENGTH_7              594
#define IDB_GROUNDAPPLYRAIN             594
#define ID_BRUSHSTRENGTH_6              595
#define IDB_VIEWFOREST                  595
#define ID_BRUSHSTRENGTH_5              596
#define IDB_GROUNDPAINT                 596
#define ID_BRUSHSTRENGTH_4              597
#define IDB_PAINTVIEW                   597
#define ID_BRUSHSTRENGTH_3              598
#define IDB_PVALL                       598
#define ID_BRUSHSTRENGTH_2              599
#define IDB_PVMONO                      599
#define ID_BRUSHSTRENGTH_1              600
#define IDB_PVCOLOR                     600
#define IDR_MENUBRUSHEFFECT             601
#define IDB_PVGLOW                      601
#define ID_BRUSHEFFECT_ADDBUMPS         602
#define IDR_MENUBRUSHEFFECTTEXT         602
#define IDB_PVSPEC                      602
#define ID_BRUSHEFFECT_SHARPEN          603
#define IDB_PVBUMP                      603
#define IDR_MENUBRUSHEFFECTPAINT        603
#define ID_BRUSHEFFECT_BLUR             604
#define IDB_PVTRANS                     604
#define ID_BRUSHEFFECT_RAISETOMAXIMUM   605
#define IDB_PVMIRROR                    605
#define ID_BRUSHEFFECT_LOWERTOMINIMUM   606
#define IDB_NEWANIMWAVE                 606
#define ID_BRUSHEFFECT_RAISE            607
#define IDB_ANIMPLAYAUDIO               607
#define ID_BRUSHEFFECT_LOWER            608
#define IDB_OBJSHOWEDITOR               608
#define ID_BRUSHEFFECT_ADDBUMPS609      609
#define IDB_OBJMERGE1                   609
#define IDB_PMSHOWBACKGROUND            609
#define ID_BRUSHEFFECT_ADDB             610
#define IDB_PMEDITVERT                  610
#define IDB_PMEDITSIDE                  611
#define IDC_CURSORBRUSH32               612
#define IDB_PMEDITEDGE                  612
#define IDC_CURSORBRUSH16               613
#define IDR_MMLGROUNDSET                613
#define IDB_PMMODEPOLY                  613
#define IDC_CURSORBRUSH8                614
#define IDR_MMLGROUNDELEV               614
#define IDB_PMMODECLAY                  614
#define IDC_CURSORBRUSH4                615
#define IDR_MMLGROUNDDETAIL             615
#define IDB_PMMODEBONE                  615
#define IDC_CURSORBRUSH64               616
#define IDB_PMMODEMORPH                 616
#define IDR_MMLGROUNDSCALE              617
#define IDC_CURSORPLAYAUDIO             617
#define IDB_PMMODETEXTURE               617
#define IDR_MMLGROUNDTEXT               618
#define IDC_CURSOROBJSHOWEDITOR         618
#define IDB_PMMODETAILOR                618
#define IDR_MMLGROUNDPAINT              619
#define IDB_PMMIRROR                    619
#define IDR_MMLGROUNDFOREST             620
#define IDB_OBJCONTROLNSEW1             620
#define IDB_PMMOVEPERP                  621
#define IDR_MML3                        622
#define IDR_HTUTORIALGROUND9            622
#define IDB_PMMOVEPERPIND               622
#define IDR_HTUTORIALGROUND8            623
#define IDB_PMMOVESCALE                 623
#define IDR_HTUTORIALGROUND7            624
#define IDB_PMMOVEROTPERP               624
#define IDR_HTUTORIALGROUND6            625
#define IDB_PMMOVEROTNONPERP            625
#define IDR_HTUTORIALGROUND5            626
#define IDB_PMEXTRA                     626
#define IDR_HTUTORIALGROUND4            627
#define IDB_PMCOLLAPSE                  627
#define IDR_HTUTORIALGROUND3            628
#define IDB_PMTESSELATE                 628
#define IDR_HTUTORIALGROUND2            629
#define IDB_PMEDGESPLIT                 629
#define IDR_HTUTORIALGROUND1            630
#define IDB_PMSIDESPLIT                 630
#define IDR_HGROUNDWEATHER              631
#define IDB_PMNEWSIDE                   631
#define IDR_HGROUNDPAINTELEV            632
#define IDB_PMSIDEEXTRUDE               632
#define IDB_PMSIDEINSET                 633
#define IDB_PMSIDEDISCONNECT            634
#define IDB_PMBEVEL                     635
#define IDR_HTUTORIALTREE8              636
#define IDB_PMSTENCIL                   636
#define IDR_HTUTORIALTREE7              637
#define IDB_PMMAGSIZE                   637
#define IDR_HTUTORIALTREE6              638
#define IDB_PMMAGANY                    638
#define IDR_HTUTORIALTREE5              639
#define IDB_PMMAGNORM                   639
#define IDR_HTUTORIALTREE3              640
#define IDB_PMMAGVIEWER                 640
#define IDR_HTUTORIALTREE4              641
#define IDB_PMMAGPINCH                  641
#define IDR_HTUTORIALTREE2              642
#define IDB_PMTEXTTOGGLE                642
#define IDR_HTUTORIALTREE1              643
#define IDB_PMTEXTPLANE                 643
#define IDR_JPG1                        644
#define IDB_PMTEXTCYLINDER              644
#define IDB_PMTEXTSPHERE                645
#define IDB_PMTEXTMOVE                  646
#define IDB_PMTEXTROT                   647
#define IDB_PMTEXTMIRROR                648
#define IDB_PMTAILORNEW                 649
#define IDB_BONEDEFAULT                 650
#define IDB_BONEROTATE                  651
#define IDB_BONENEW                     652
#define IDI_PAINTICON                   802
#define IDR_MMLPAINTADD                 803
#define IDR_MMLPAINTTEXT                804
#define IDR_MMLPAINTMOD                 805
#define IDR_MMLPAINTDIALOG              806
#define IDR_HTUTORIALPAINT8             807
#define IDR_HTUTORIALPAINT7             808
#define IDR_HTUTORIALPAINT6             809
#define IDR_HTUTORIALPAINT5             810
#define IDR_HTUTORIALPAINT4             811
#define IDR_HTUTORIALPAINT3             812
#define IDR_HTUTORIALPAINT2             813
#define IDR_HTUTORIALPAINT1             814
#define IDR_HANIMLIPSYNC                815
#define IDR_MML5                        816
#define IDR_HANIMPLAYAUDIO              816
#define IDR_MMLPOLYMESHDIALOG           818
#define IDR_MENUPOLYMESHSYM             819
#define ID_SYMMETRY_LEFT                820
#define ID_SYMMETRY_FRONT               821
#define ID_SYMMETRY_TOP                 822
#define IDC_CURSORPMMOVEPERP            824
#define IDC_CURSORPMMOVEPERPIND         825
#define IDR_MMLPMMOVEVERT               825
#define IDC_CURSORPMMOVEROTNONPERP      826
#define IDR_MENUPMEXTRA                 826
#define IDC_CURSORPMMOVEROTPERP         827
#define ID_PMEXTRA_MAKETHESIDEPLANAR    827
#define IDC_CURSORPMMOVESCALE           828
#define ID_PMEXTRA_FLIPTHESIDE          828
#define ID_PMEXTRA_ROTATETHESIDE        829
#define IDC_CURSORPMCOLLAPSE            829
#define IDR_MENUPMTESSELATE             830
#define IDC_CURSORPMEDGESPLIT           830
#define ID_TESSELATE_DIVIDEQUADRILATERALSINTOTRIANGLES 831
#define IDC_CURSORPMSIDESPLIT           831
#define IDR_MENUBRUSHSHAPEPM            831
#define ID_TESSELATE_DIVIDEUSINGEXISTINGVERTICES 832
#define IDC_CURSORPMNEWSIDE             832
#define ID_TESSELATE_DIVIDETHROUGHTHEEDGECENTERS 833
#define IDC_CURSORPMSIDEEXTRUDE         833
#define IDC_CURSORPMSIDEINSET           834
#define IDR_MENUBRUSHEFFECTPM           834
#define IDC_CURSORPMSIDEDISCONNECT      835
#define ID_BRUSHEFFECTPOLYMESH_ADDHEIGHT 835
#define IDC_CURSORPMBEVEL               836
#define ID_BRUSHEFFECTPOLYMESH_REMOVEHEIGHT 836
#define ID_BRUSHEFFECTPOLYMESH_PULLTOWARDSYOU 837
#define IDC_CURSORPMMAGANY              837
#define ID_BRUSHEFFECTPOLYMESH_PUSHAWAYFROMYOU 838
#define IDC_CURSORPMMAGNORM             838
#define ID_BRUSHEFFECTPOLYMESH_SMOOTH   839
#define IDC_CURSORPMMAGVIEWER           839
#define ID_BRUSHEFFECTPOLYMESH_ROUGHEN  840
#define IDC_CURSORPMMAGPINCH            840
#define IDC_CURSORPMTEXTMOVE            841
#define IDR_MENUPMSTENCIL               842
#define IDC_CURSORPMTEXTROT             842
#define ID_STENCIL_NOSTENCILING         843
#define IDR_MENUPMMAGSIZE               843
#define IDC_CURSORPMTAILORNEW           843
#define ID_STENCIL_STENCILBASEDONRED    844
#define IDC_CURSORBONEROTATE            844
#define ID_STENCIL_STENCILBASEDONGREEN  845
#define IDC_CURSORBONEROTATE1           845
#define IDC_CURSORBONENEW               845
#define ID_STENCIL_STENCILBASEDONBLUE   846
#define ID_STENCIL_STENCILBASEDONBRIGHTNESS 847
#define ID_STENCIL_REVERSESTENCIL       848
#define ID_MAGSIZE_EXTRALARGE           849
#define ID_MAGSIZE_LARGE                850
#define ID_MAGSIZE_MEDIUM               851
#define ID_MAGSIZE_SMALL                852
#define ID_MAGSIZE_EXTRASMALL           853
#define IDR_MENUPMORGEXTRA              854
#define ID_EXTRA_FLIPLEFTANDRIGHT       855
#define IDR_MENUBRUSHEFFECTPMMORPH      855
#define ID_EXTRA_FLIPFRONTANDBACK       856
#define IDR_MENUBRUSHEFFECTPMTAILOR     856
#define ID_EXTRA_FLIPTOPANDBOTTOM       857
#define ID_EXTRA_ADDMOREDETAIL          858
#define ID_EXTRA_MIRRORFROMTHERIGHTSIDETOTHELEFT 859
#define ID_EXTRA_MIRRORFROMTHELEFTSIDETOTHERIGHT 860
#define ID_EXTRA_MIRRORFROMTHEBACKTOTHEFRONT 861
#define ID_EXTRA_MIRRORFROMTHEFRONTTOTHEBACK 862
#define ID_EXTRA_MIRRORFROMTHETOPTOTHEBOTTOM 863
#define ID_EXTRA_MIRRORFROMTHEBOTTOMTOTHETOP 864
#define ID_BRUSHEFFECTMORPH_INCREASEMORPH 865
#define ID_BRUSHEFFECTMORPH_DECREASEMORPH 866
#define ID_BRUSHEFFECTMORPH_ERASEMORPH  867
#define IDR_MMLPOLYMESHTEXTURE          868
#define IDR_MMLPMTEXTMOVEVERT           870
#define IDR_MMLPMTEXTMIRROR             871
#define ID_BRUSHEFFECTTAILOR_USETHEPAINTEDAREFORTHECLOTHING 872
#define ID_BRUSHEFFECTTAILOR_REMOVETHEPAINTEDAREAFROMTHECLOTHING 873
#define IDR_MENUPMBONEEXTRA             874
#define ID_BONEEXTRA_RESTOREAUTOMATICBONEWEIGHTS 875
#define IDR_MENUBRUSHEFFECTPMBONE       875
#define ID_BRUSHEFFECTBONE_INCREASEBONEWEIGHT 876
#define ID_BRUSHEFFECTBONE_DECREASEBONEWEIGHT 877
#define ID_BRUSHEFFECTBONE_SETBONEWEIGHT 878
#define ID_BRUSHEFFECTBONE_CLEARBONEWEIGHT 879
#define ID_BONEEXTRA_MIRRORBONEWEIGHTSFROMRIGHTTOLEFT 880
#define ID_BONEEXTRA_MIRRORBONEWEIGHTSFROMLEFTTORIGHT 881
#define ID_BONEEXTRA_MIRRORBONEWEIGHTSFROMBACKTOFRONT 882
#define ID_BONEEXTRA_MIRRORBONEWEIGHTSFROMFRONTTOBACK 883
#define ID_BONEEXTRA_MIRRORBONEWEIGHTSFROMTOPTOBOTTOM 884
#define ID_BONEEXTRA_MIRRORBONEWEIGHTSFROMBOTTOMTOTOP 885
#define ID_BONEEXTRA_COPYBONEWEIGHTSFROMRIGHTTOLEFT 886
#define ID_BONEEXTRA_COPYBONEWEIGHTSFROMLEFTTORIGHT 887
#define ID_BONEEXTRA_COPYBONEWEIGHTSFROMBACKTOFRONT 888
#define ID_BONEEXTRA_COPYBONEWEIGHTSFROMFRONTTOBACK 889
#define ID_BONEEXTRA_COPYBONEWEIGHTSFROMTOPTOBOTTOM 890
#define ID_BONEEXTRA_COPYBONEWEIGHTSFROMBOTTOMTOTOP 891
#define IDR_HTUTORIALPM21               892
#define IDR_HTUTORIALPM1                893
#define IDR_HTUTORIALPM2                894
#define IDR_HTUTORIALPM3                895
#define IDR_HTUTORIALPM4                896
#define IDR_HTUTORIALPM5                897
#define IDR_HTUTORIALPM6                898
#define IDR_HTUTORIALPM7                899
#define IDR_HTUTORIALPM8                900
#define IDR_HTUTORIALPM9                901
#define IDR_HTUTORIALPM10               902
#define IDR_HTUTORIALPM11               903
#define IDR_HTUTORIALPM12               904
#define IDR_HTUTORIALPM13               905
#define IDR_HTUTORIALPM14               906
#define IDR_HTUTORIALPM15               907
#define IDR_HTUTORIALPM16               908
#define IDR_HTUTORIALPM17               909
#define IDR_HTUTORIALPM18               910
#define IDR_HTUTORIALPM19               911
#define IDR_HTUTORIALPM20               912
#define IDR_HTUTORIALBONE9              913
#define IDR_HTUTORIALBONE1              914
#define IDR_HTUTORIALBONE2              915
#define IDR_HTUTORIALBONE3              916
#define IDR_HTUTORIALBONE4              917
#define IDR_HTUTORIALBONE5              918
#define IDR_HTUTORIALBONE6              919
#define IDR_HTUTORIALBONE7              920
#define IDR_HEYES                       922
#define IDR_HHAIRLOCK                   923
#define IDR_HHAIRHEAD                   924
#define IDR_HTOOTH                      925
#define IDR_HJAW                        926
#define IDR_MML4                        927
#define IDR_HTUTORIALCHAR1              927
#define ID_LIBRARY_EFFECTS              928
#define IDR_MML6                        929
#define IDR_HEFFECTS                    929
#define IDR_HGRASS                      930
#define IDR_HWATERFALL                  931
#define IDR_HRIVER                      932
#define IDR_HROCK                       933
#define IDR_HTUTORIALCAVE1              934
#define IDR_HTUTORIALCAVE2              935
#define IDR_HTUTORIALCAVE3              936
#define IDR_HTUTORIALCAVE4              937
#define IDR_HTUTORIALCAVE5              938
#define IDR_HTUTORIALCAVE6              939
#define IDR_MML7                        940
#define IDR_HTUTORIALCAVE7              940
#define ID_TOP                          40001
#define ID_FROMTHENORTH                 40002
#define ID_FROMTHEEAST                  40003
#define ID_FROMTHESOUTH                 40004
#define ID_FROMTHEWEST                  40005
#define ID_QUICK_NORTHEAST              40006
#define ID_QUICK_SOUTHEAST              40007
#define ID_QUICK_SOUTHWEST              40008
#define ID_QUICK_NORTHWEST              40009
#define ID_QUICK_EASTELEVATED           40010
#define ID_QUICK_NORTHELEVATED          40013
#define ID_QUICK_SOUTHELEVATED          40014
#define ID_QUICK_WESTELEVATED           40015
#define ID_QUICK_NORTHEASTELEVATED      40016
#define ID_QUICK_SOUTHEASTELEVATED      40017
#define ID_QUICK_SOUTHWESTELEVATED      40018
#define ID_QUICK_NORTHWESTELEVATED      40019
#define ID_LEVEL_GROUNDFLOOR            40020
#define ID_LEVEL_1STFLOOR               40021
#define ID_LEVEL_BASEMENT               40022
#define ID_LEVEL_2NDFLOOR               40023
#define ID_LEVEL_ALL                    40024
#define ID_LEVEL_3RDFLOOR               40025
#define ID_LEVEL_4THFLOOR               40026
#define ID_LEVEL_5THFLOOR               40027
#define ID_LEVEL_6THFLOOR               40028
#define ID_LEVEL_7THFLOOR               40029
#define ID_LEVEL_8THFLOOR               40030
#define ID_LEVEL_9THFLOOR               40031
#define ID_QUALITY_LOW                  40032
#define ID_QUALITY_POOR                 40033
#define ID_QUALITY_GOOD                 40034
#define ID_QUALITY_HIGH                 40035
#define ID_QUALITY_BEST                 40036
#define ID_QUALITY_LOWRES               40037
#define ID_QUALITY_NORMALRES            40038
#define ID_QUALITY_HIGHRES              40039
#define ID_QUALITY_VERYLOW              40040
#define ID_QUICK_ADDTOFAVORITES         40041
#define ID_QUICK_REMOVEFROMFAVORITES    40042
#define ID_QUALITY_LIGHTINGEXPOSURE_FULLSUNLIGHT 40043
#define ID_QUALITY_LIGHTINGEXPOSURE_OVERCAST 40044
#define IDQUALITY_LIGHTINGEXPOSURE_BRIGHTINDOORS 40044
#define ID_QUALITY_LIGHTINGEXPOSURE_DARKINDOORS 40045
#define ID_QUALITY_LIGHTINGEXPOSURE_MOONLIGHT 40046
#define ID_QUALITY_LIGHTINGEXPOSURE_DARKNIGHTTIMEINTERIOR 40047
#define ID_QUALITY_LIGHTINGEXPOSURE_UNDEREXPOSEDINSUNLIGHT 40048
#define ID_LIBRARY_TEXTURES             40049
#define ID_LIBRARY_OBJECTS              40050
#define ID_THUMBNAIL_NOTHUMBNAILS       40051
#define ID_THUMBNAIL_THUMBAILSONTHERIGHT 40052
#define ID_THUMBNAIL_THUMBNAILSONTHEBOTTOM 40053
#define ID_THUMBNAIL_SETUPTHUMBNAILSTOOL 40054

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        941
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           801
#endif
#endif
