//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Dragonfly.rc
//
#define IDI_ICON1                       101
#define IDI_APPICON                     101
#define IDR_MMLLOGONFIRSTTIME           106
#define IDR_MMLLOGONNEWUSER             107
#define IDR_MMLLOGONASKUSER             108
#define IDR_MMLTODAY                    109
#define IDR_BACKGROUND                  110
#define IDR_MMLNYI                      111
#define IDR_MMLCALENDAR                 112
#define IDR_MMLMEETINGS                 113
#define IDR_MMLREMINDERS                114
#define IDR_MMLTASKS                    115
#define IDR_MMLNOTES                    116
#define IDR_MMLPHONE                    117
#define IDR_MMLPEOPLE                   118
#define IDR_MMLBILLING                  120
#define IDR_MMLJOURNAL                  121
#define IDR_MMLMEMORYLANE               122
#define IDR_MMLPHOTOS                   123
#define IDR_MMLARCHIVE                  124
#define IDR_MMLNUMERICALRECORDS         125
#define IDR_MMLANALYSIS                 126
#define IDR_MMLDEEPTHOUGHTS             127
#define IDR_MMLSEARCH                   128
#define IDR_MMLMISC                     129
#define IDR_MMLABOUT                    130
#define IDR_MMLOVERVIEW                 131
#define IDR_MMLTHEORY                   133
#define IDR_MMLBUGS                     134
#define IDR_MMLHISTORY                  135
#define IDR_MMLREGISTER                 136
#define IDR_MMLTTS                      137
#define IDR_MMLNEWPERSON                138
#define IDR_MMLLOGONFROMBACKUP          139
#define IDR_MMLLOGONDELETE              140
#define IDR_MMLPEOPLELOOKUP             141
#define IDR_MMLPEOPLELIST               142
#define IDR_MMLPEOPLEREMOVE             143
#define IDR_MMLPEOPLEINFO               144
#define IDR_MMLPROJECT                  145
#define IDR_MMLPROJECTADD               146
#define IDR_MMLPROJECTREMOVE            147
#define IDR_MMLPROJECTVIEW              148
#define IDR_MMLPROJECTTASKADD           149
#define IDR_MMLPROJECTTASKADDMULTILE    150
#define IDR_MMLPROJECTNEWSUBPROJECT     151
#define IDR_MMLPROJECTTASKEDIT          152
#define IDB_UPARROW                     154
#define IDB_DOWNARROW                   155
#define IDR_MMLPROJECTINFO              155
#define IDB_SPACEARROW                  156
#define IDR_MMLREMINDERINFO             156
#define IDR_MMLTASKADD                  157
#define IDR_MMLTASKEDIT                 158
#define IDR_MMLREOCCUR                  159
#define IDR_MMLTASKADDREOCCUR           160
#define IDR_MMLTASKEDITREOCCUR          161
#define IDR_MMLTASKINFO                 162
#define IDR_MMLPERSONVIEW               163
#define IDR_MMLPERSONADDEDITINCLUDE     164
#define IDR_MMLPERSONEDIT               165
#define IDR_MMLPERSONQUICKADD           166
#define IDR_MMLMEETINGADD               167
#define IDR_MMLMEETINGADDREOCCUR        168
#define IDR_MMLMEETINGEDIT              169
#define IDR_MMLMEETINGEDITREOCCUR       170
#define IDR_MMLMEETINGNOTESEDIT         171
#define IDR_MMLMEETINGNOTESVIEW         172
#define IDR_MMLMEETINGACTIONOTHER       173
#define IDR_MMLMEETINGACTIONSELF        174
#define IDR_MMLMEETINGINFO              175
#define IDR_MMLPHONEMAKECALL            176
#define IDR_MMLPHONENOTESEDIT           177
#define IDR_MMLPHONENOTESVIEW           178
#define IDR_MMLPHONECALLLOG             179
#define IDR_MMLPHONESPEEDNEW            180
#define IDR_MMLPHONESPEEDREMOVE         181
#define IDR_MMLPHONEINFO                182
#define IDR_MMLCALENDARINFO             183
#define IDR_MMLCALENDARLOG              184
#define IDR_MMLTOMORROW                 185
#define IDR_MMLTODAYINFO                186
#define IDR_MMLIFYOULIKE                187
#define IDR_MMLJOURNALCATADD            188
#define IDR_MMLJOURNALCATREMOVE         189
#define IDR_MMLJOURNALCAT               190
#define IDR_MMLJOURNALENTRYEDIT         191
#define IDR_MMLJOURNALENTRYVIEW         192
#define IDR_MMLJOURNALINFO              194
#define IDR_MMLMEMORYEDIT               195
#define IDR_MMLMEMORYVIEW               196
#define IDR_MMLMEMORYQUICKADD           197
#define IDR_MMLMEMORYLIST               198
#define IDR_MMLMEMORYSUGGEST            199
#define IDR_LOGO                        200
#define IDR_MMLMEMORYINFO               200
#define IDR_MMLMACROS                   201
#define IDR_LOGIN                       201
#define IDR_MMLTEMPLATE                 202
#define IDR_MMLTEMPLATE2                203
#define IDR_MMLTEMPLATE3                204
#define IDR_ARCHIVE                     206
#define IDR_JPGREMINDERS                207
#define IDR_JPGTASKS                    208
#define IDR_JPGPROJECTS                 209
#define IDR_JPGPHONE                    210
#define IDR_JPGNOTES                    211
#define IDR_JPGJOURNAL                  212
#define IDR_JPGTODAY                    213
#define IDR_JPGCALENDAR                 214
#define IDR_JPGMISC                     215
#define IDR_JPGSEARCH                   216
#define IDR_JPGPEOPLE                   217
#define IDR_JPGMEMORYLANE               218
#define IDR_JPGDEEPTHOUGHTS             219
#define IDR_MMLWRAPUP                   220
#define IDR_JPGWRAPUP                   221
#define IDR_JPGMEETING                  222
#define IDR_MMLDEEPPEOPLE               223
#define IDR_MMLDEEPSHORT                224
#define IDR_MMLDEEPLONG                 225
#define IDR_MMLDEEPCHANGE               226
#define IDR_MMLDEEPWORLD                227
#define IDR_MMLWRAPUPEDIT               228
#define IDR_MMLWRAPUPVIEW               229
#define IDR_MMLSEARCHINFO               230
#define IDR_MMLARCHIVEOPTIONS           231
#define IDR_MMLARCHIVELIST              232
#define IDR_MMLARCHIVEVIEW              233
#define IDR_MMLARCHIVEINFO              234
#define IDI_ARCHIVE                     235
#define IDB_ARCHIVE                     236
#define IDR_MMLCALENDARHOLIDAYS         237
#define IDB_X                           237
#define IDR_MMLPEOPLEPRINT              238
#define IDR_MMLCALENDARLIST             239
#define IDR_MMLBACKUP                   240
#define IDR_MMLCHANGEPASSWORD           241
#define IDR_MMLMISCUI                   242
#define IDR_MMLPEOPLEIMPORT             243
#define IDR_MMLJOURNALQUICKADD          244
#define IDR_MMLHOWLONG                  246
#define IDR_MMLNOTESADDCATEGORY         247
#define IDR_MMLJOURNALTIMEREND          248
#define IDR_MMLNOTESEDIT                249
#define IDR_MMLARCHIVEEDIT              250
#define IDR_MMLPHONEWHICHNUMBER         251
#define IDR_MMLTOC                      252
#define IDR_MMLFAVORITESADD             253
#define IDR_MMLFAVORITES                254
#define IDR_MMLFAVORITESEDIT            255
#define IDR_MMLNOTESQUICKADD            256
#define IDR_MMLREMINDERQUICKADD         257
#define IDR_MMLCALENDARCOMBO            258
#define IDR_MMLBUSINESSQUICKADD         259
#define IDR_MMLPERSONBUSINESSQUICKADD   260
#define IDR_MMLBUSINESSADDEDITINCLUDE   261
#define IDR_MMLNEWBUSINESS              262
#define IDR_MMLBUSINESSEDIT             263
#define IDR_MMLBUSINESSVIEW             264
#define IDR_MMLCALENDARSUMMARY          265
#define IDR_MMLPHONESCHEDADD            266
#define IDR_MMLPHONESCHEDEDIT           267
#define IDR_MMLPHONESCHEDADDREOCCUR     268
#define IDR_MMLPHONESCHEDEDITREOCCUR    269
#define IDR_MMLCALENDARYEARLY           270
#define IDR_MMLPASSWORD                 271
#define IDR_MMLPASSWORDEDIT             272
#define IDR_MMLPASSWORDADD              273
#define IDR_MMLPASSWORDVERIFY           274
#define IDR_MMLTIMEZONES                275
#define IDR_MMLTIMEMOON                 276
#define IDB_EARTH                       277
#define IDR_MMLTIMESUNLIGHT             278
#define IDR_MMLEVENT                    280
#define IDR_MMLEVENTADD                 281
#define IDR_MMLEVENTEDIT                282
#define IDR_MMLPHOTOSINFO               284
#define IDR_MMLPHOTOSADD                285
#define IDR_MMLPHOTOSENTRYVIEW          286
#define IDR_MMLPHOTOSENTRYEDIT          287
#define IDR_MMLPLANNER                  288
#define IDR_MMLPLANNERINFO              289
#define IDR_MMLPLANNERMENU              290
#define IDR_MMLPLANNERBREAKS            291
#define IDR_MMLALARM                    292
#define IDR_MMLREMINDERADDREOCCUR       293
#define IDR_MMLTIMEZONEADD              294
#define IDR_MMLPEOPLEEXPORT             295
#define IDR_MMLHISTORY1                 296
#define IDR_MMLCALENDARYEARLY2          297
#define IDR_MMLPAGEERROR                298
#define IDR_MMLPASSWORDSUSPEND          299
#define IDR_MMLPASSWORDSUSPENDVERIFY    300
#define IDR_MMLTEMPLATER                301
#define IDR_MMLPROJECTTASKSPLIT         302
#define IDR_MMLQUOTES                   303

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        304
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
