//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MIFClient.rc
//
#define IDI_APPICON                     101
#define IDC_CURSOREYE                   103
#define IDC_CURSORHAND                  104
#define IDC_CURSOR1                     105
#define IDC_CURSORROTLEFT               106
#define IDC_CURSORROTRIGHT              107
#define IDC_CURSORROTUP                 108
#define IDI_SPEAKERICON                 108
#define IDC_CURSORROTDOWN               109
#define ID_VERBWINDOW_CUSTOMIZETOOLBAR  109
#define IDI_ICONTALKTO                  109
#define IDC_CURSORMOUTH                 110
#define IDI_ICONWHISPERTO               110
#define IDC_CURSORMENU                  111
#define IDI_ICONYELL                    111
#define IDC_CURSORWALK                  112
#define IDI_MINIMENUICON                112
#define IDR_MMLTRANSCRIPT               113
#define IDC_CURSORTALK                  113
#define IDR_MMLMRUPAGE                  115
#define IDR_MMLEULAPAGE                 116
#define IDR_MMLSHARDPAGE                117
#define IDR_MMLIPADDRPAGE               118
#define IDR_MMLLOGONPAGE                120
#define IDR_MMLPASSWORD2PAGE            121
#define IDR_MMLRELOGONPAGE              122
#define IDB_BLOODLARGE                  123
#define IDB_BLOODMED                    124
#define IDR_MENUMAINMENU                124
#define IDB_BLOODSMALL                  125
#define IDB_BLOODLARGE1                 125
#define ID_MAINMENU_SHOW                125
#define IDB_STUNLARGE                   126
#define ID_MAINMENU_WINDOWS             126
#define IDB_STUNMED                     127
#define ID_MAINMENU_EXIT                127
#define IDB_STUNSMALL                   128
#define ID_MAINMENU_RESETWINDOWLOCATIONS 128
#define IDB_TISSUELARGE                 129
#define IDR_ACCELERATOR                 129
#define IDB_TISSUEMED                   130
#define IDR_MMLREADME                   130
#define IDB_TISSUESMALL                 131
#define IDC_CURSORZOOM                  131
#define IDB_BONEBROKEN                  132
#define IDB_SEVERED                     133
#define IDR_WAVETORCH3                  133
#define IDB_FACEHAPPY                   134
#define IDR_WAVETORCH1                  134
#define IDB_FACEDAZED                   135
#define IDR_WAVETORCH2                  135
#define IDB_FACEUNC                     136
#define IDR_WAVERAINHEAVY1              136
#define IDB_FACEDEAD                    137
#define IDR_WAVERAINHEAVY2              137
#define IDB_ATTACKSTYPESWING            138
#define IDR_WAVERAINHEAVY3              138
#define IDB_ATTACKSTYPESTAB             139
#define IDR_WAVERAINLIGHT1              139
#define IDB_ATTACKSTYPESHOOT            140
#define IDR_WAVERAINLIGHT2              140
#define IDB_ATTACKSTYPEPUNCH            141
#define IDR_WAVERAINLIGHT3              141
#define IDB_ATTACKSTYPEGORE             142
#define IDR_WAVETHUNDER1                142
#define IDB_ATTACKSTYPEBITE             143
#define IDR_WAVETHUNDER2                143
#define IDB_ATTACKSTYPETAILSLAP         144
#define IDR_WAVETHUNDER3                144
#define IDB_ATTACKSTYPECLAW             145
#define IDR_WAVETHUNDER4                145
#define IDB_ATTACKSTYPEPUSH             146
#define IDR_WAVETHUNDER5                146
#define IDB_ATTACKSTYPEKICK             147
#define IDR_WAVEWINDHEAVY1              147
#define IDB_ATTACKSTYPETHROW            148
#define IDR_WAVEWINDHEAVY2              148
#define IDB_ACTIONGOOD1                 149
#define IDR_WAVEWINDHEAVY3              149
#define IDB_ACTIONGOOD2                 150
#define IDR_WAVEWINDLIGHT1              150
#define IDB_ACTIONGOOD3                 151
#define IDR_WAVEWINDLIGHT2              151
#define IDB_ACTIONBAD1                  152
#define IDR_WAVEWINDLIGHT3              152
#define IDB_ACTIONBAD2                  153
#define IDR_WAVEWINDMED1                153
#define IDB_ACTIONBAD3                  154
#define IDR_WAVEWINDMED2                154
#define IDB_ATTACKLOCHEAD               155
#define IDR_WAVEWINDMED3                155
#define IDB_ATTACKLOCCHEST              156
#define IDR_WAVEWINDLIGHT5              156
#define IDB_ATTACKLOCARM                157
#define IDR_WAVEWINDLIGHT4              157
#define IDB_ATTACKLOCLEG                158
#define IDR_WAVEKOOKABURRA1             158
#define IDB_ATTACKLOCTAIL               159
#define IDR_WAVEAVIARYBIRD4             159
#define IDB_ATTACKLOCWING               160
#define IDR_WAVEAVIARYBIRD7             160
#define IDB_DEFENDPARRY                 161
#define IDR_WAVEBARKINGOWL2             161
#define IDB_DEFENDPARRYNOT              162
#define ID_MAINMENU_IMAGEDETAIL         162
#define IDB_DEFENDDODGE                 163
#define ID_IMAGEDETAIL_VERYLOW          163
#define IDB_DEFENDDODGENOT              164
#define ID_IMAGEDETAIL_LOW              164
#define IDB_DEFENDARMOR                 165
#define ID_IMAGEDETAIL_NORMAL           165
#define IDB_DEFENDARMORNOT              166
#define ID_IMAGEDETAIL_HIGH             166
#define IDB_DEFENDKNOCKDOWN             167
#define ID_IMAGEDETAIL_VERYHIGH         167
#define IDB_DEFENDDROPITEM              168
#define IDB_DEFENDUL                    169
#define IDR_MMLRENDERQUALITY            169
#define IDB_DEFENDUC                    170
#define ID_MAINMENU_IMAGEDETAIL170      170
#define IDB_DEFENDUR                    171
#define IDR_MENU360CONTEXT              171
#define IDB_DEFENDML                    172
#define ID_CONTEXT360_ZOOMIN            172
#define IDR_MENUTASKBAR                 172
#define IDB_DEFENDMC                    173
#define ID_CONTEXT360_ZOOMOUT           173
#define IDB_DEFENDMR                    174
#define IDC_CURSORNO                    174
#define IDB_DEFENDLL                    175
#define IDC_CURSORNOMENU                175
#define IDB_DEFENDLC                    176
#define IDC_CURSORDOOR                  176
#define IDB_DEFENDLR                    177
#define IDC_CURSORKEY                   177
#define ID_MAINMENU_UPLOADANIMAGEOFYOURCHARACTER 177
#define ID_MAINMENU_OPTIONS             178
#define IDB_BBSREAD                     178
#define IDC_CURSORWALKDONT              178
#define IDR_MMLUPLOADIMAGE              179
#define IDB_BBSUNREAD                   179
#define IDC_CURSORPOINTRIGHT            179
#define IDB_BBSLOCKED                   180
#define ID_MAINMENU_VOICECHATSETTINGS   180
#define IDC_CURSORPOINTRIGHT1           180
#define IDC_CURSORPOINTLEFT             180
#define IDB_BBSPOLL                     181
#define IDR_WAVEHMMM                    181
#define IDC_CURSOR360SCROLL             181
#define IDB_SPEAKER                     182
#define IDR_WAVEYAWN                    182
#define IDC_CURSOR360SCROLL1            182
#define IDC_CURSOR360SCROLLON           182
#define IDR_WAVEWHISTLE3                183
#define IDR_WAVEWHISTLE2                184
#define IDR_WAVEWHISTLE1                185
#define IDR_WAVEBURP                    186
#define IDR_WAVEKISS                    187
#define IDR_WAVECOMBATSWORDSWORDSTABM   188
#define IDR_WAVECOMBATBOWFIRE           189
#define IDR_WAVECOMBATCHAINBOWH         190
#define IDR_WAVECOMBATCHAINBOWL         191
#define IDR_WAVECOMBATCHAINBOWM         192
#define IDR_WAVECOMBATCHAINCLUBH        193
#define IDR_WAVECOMBATCHAINCLUBL        194
#define IDR_WAVECOMBATCHAINCLUBM        195
#define IDR_WAVECOMBATCHAINFISTH        196
#define IDR_WAVECOMBATCHAINFISTL        197
#define IDR_WAVECOMBATCHAINFISTM        198
#define IDR_WAVECOMBATCHAINSWORDSLASHH  199
#define IDR_WAVECOMBATCHAINSWORDSLASHL  200
#define IDR_WAVECOMBATCHAINSWORDSLASHM  201
#define IDR_WAVECOMBATCHAINSWORDSTABH   202
#define IDR_WAVECOMBATCHAINSWORDSTABL   203
#define IDR_WAVECOMBATCHAINSWORDSTABM   204
#define IDR_WAVECOMBATCLUBCLUBH         205
#define IDR_WAVECOMBATCLUBCLUBL         206
#define IDR_WAVECOMBATCLUBCLUBM         207
#define IDR_WAVECOMBATCLUBSWORDH        208
#define IDR_WAVECOMBATCLUBSWORDL        209
#define IDR_WAVECOMBATCLUBSWORDM        210
#define IDR_WAVECOMBATMISSBOWH          211
#define IDR_WAVECOMBATMISSBOWL          212
#define IDR_WAVECOMBATMISSBOWM          213
#define IDR_WAVECOMBATMISSSWINGH        214
#define IDR_WAVECOMBATMISSWINGL         215
#define IDR_WAVECOMBATMISSSWINGL        215
#define IDR_WAVECOMBATMISSSWINGM        216
#define IDR_WAVECOMBATPAINHIGHFEMALE    217
#define IDR_WAVECOMBATPAINHIGHMALE      218
#define IDR_WAVECOMBATPAINLOWFEMALE     219
#define IDR_WAVECOMBATPAINLOWMALE       220
#define IDR_WAVECOMBATPAINMEDFEMALE     221
#define IDR_WAVECOMBATPAINMEDMALE       222
#define IDR_WAVECOMBATSHIELDBOWH        223
#define IDR_WAVECOMBATSHIELDBOWL        224
#define IDR_WAVECOMBATSHIELDBOWM        225
#define IDR_WAVECOMBATSHIELDCLUBH       226
#define IDR_WAVECOMBATSHIELDCLUBL       227
#define IDR_WAVECOMBATSHIELDCLUBM       228
#define IDR_WAVECOMBATSHIELDFISTH       229
#define IDR_WAVECOMBATSHIELDFISTL       230
#define IDR_WAVECOMBATSHIELDFISTM       231
#define IDR_WAVECOMBATSHIELDSWORDSLASHH 232
#define IDR_WAVECOMBATSHIELDSWORDSLASHL 233
#define IDR_WAVECOMBATSHIELDSWORDSLASHM 234
#define IDR_WAVECOMBATSHIELDSWORDSTABH  235
#define IDR_WAVECOMBATSHIELDSWORDSTABL  236
#define IDR_WAVECOMBATSHIELDsWORDSTABM  237
#define IDR_WAVECOMBATSHIELDSWORDSTABM  237
#define IDR_WAVECOMBATSKINBOWH          238
#define IDR_WAVECOMBATSKINBOWL          239
#define IDR_WAVECOMBATSKINBOWM          240
#define IDR_WAVECOMBATSKINCLUBH         241
#define IDR_WAVECOMBATSKINCLUBL         242
#define IDR_WAVECOMBATSKINCLUBM         243
#define IDR_WAVECOMBATSKINFISTH         244
#define IDR_WAVECOMBATSKINFISTL         245
#define IDR_WAVECOMBATSKINFISTM         246
#define IDR_WAVECOMBATSKINSWORDSLASHH   247
#define IDR_WAVECOMBATSKINSWORDSLASHL   248
#define IDR_WAVECOMBATSKINSWORDSLASHM   249
#define IDR_WAVECOMBATSKINSWORDSTABH    250
#define IDR_WAVECOMBATSKINSWORDSTABL    251
#define IDR_WAVECOMBATSKINSWORDSTABM    252
#define IDR_WAVECOMBATSTEELBOWH         253
#define IDR_WAVECOMBATSTEELBOWL         254
#define IDR_WAVECOMBATSTEELBOWM         255
#define IDR_WAVECOMBATSTEELCLUBH        256
#define IDR_WAVECOMBATSTEELCLUBL        257
#define IDR_WAVECOMBATSTEELCLUBM        258
#define IDR_WAVECOMBATSTEELFISTH        259
#define IDR_WAVECOMBATSTEELFISTL        260
#define IDR_WAVECOMBATSTEELFISTM        261
#define IDR_WAVECOMBATSTEELSWORDSLASHH  262
#define IDR_WAVECOMBATSTEELSWORDSLASHL  263
#define IDR_WAVECOMBATSTEELSWORDSLASHM  264
#define IDR_WAVECOMBATSTEELSWORDSTABH   265
#define IDR_WAVECOMBATSTEELSWORDSTABL   266
#define IDR_WAVECOMBATSTEELSWORDSTABM   267
#define IDR_WAVECOMBATSWORDSWORDSLASHH  268
#define IDR_WAVECOMBATSWORDSWPRDSLASHL  269
#define IDR_WAVECOMBATSWORDSWORDSLASHL  269
#define IDR_WAVECOMBATSWORDSWORDSLASHM  270
#define IDR_WAVECOMBATSWORDSWORDSTABH   271
#define IDR_WAVECOMBATSWPRDSWORDSTABL   272
#define IDR_WAVECOMBATSWORDSWORDSTABL   272
#define IDR_MMLRENDERQUALITYEASY        273
#define IDR_MMLMIFOPEN                  274
#define IDB_FOLDER                      275
#define IDR_MMLLARGETTSPAGE             276
#define ID_TASKBAR_SHOW                 277
#define ID_TASKBAR_SHOW278              278
#define ID_MAINMENU_HIDETABS            279
#define ID_MAINMENU_CUSTOMIZETOOLBAR    280
#define ID_MAINMENU_SUBTITLESIZE        281
#define ID_SUBTITLESIZE_NOSUBTITLES     282
#define ID_SUBTITLESIZE_SMALL           283
#define ID_SUBTITLESIZE_MEDIUM          284
#define ID_SUBTITLESIZE_LARGE           285
#define IDR_MMLSETTINGS                 286
#define ID_MAINMENU_SETTINGSANDOPTIONS  287
#define IDR_MMLLAYOUT                   288
#define IDR_MMLSPEECH                   289
#define ID_TASKBAR_DISPLAYONSECONDMONITOR 290
#define IDR_MMLREGISTER                 291
#define IDR_WAVEVOICESAMPLESMALL        292
#define IDR_WAVEVOICESAMPLELARGE        293
#define IDR_WAVEBOOKOPEN                294
#define IDR_WAVEBOOKPAGEFLIP            295
#define IDR_WAVE3                       296
#define IDR_WAVEBOOKCLOSE               296
#define IDR_JPGLOGO300                  297
#define IDR_MMLUSERPASSWORDFILE         298
#define IDR_MMLNEWPASSWORDFILE          299
#define IDR_MMLNEWPASSWORDASK           300
#define IDR_MMLUSERPASSWORDASK          301
#define IDR_MMLPLAYERINFO               302
#define IDR_MMLMAINPLAYERPAGE           303
#define IDR_MMLCHANGEPASSWORD           304
#define IDR_MMLDELETEPASSWORDFILE       305
#define IDR_MMLACCOUNTEDIT              306
#define IDR_MMLLINKWORLDPAGE            307
#define IDR_JPGUSERPASSWORDFILE         313
#define IDR_JPGMAINPLAYERPAGE           314
#define IDR_JPGUSERPASSWORDASK          315
#define IDR_JPGMIFOPEN                  316
#define IDR_JPGREADME                   317
#define IDR_JPGREGISTER                 318
#define IDR_JPGSHARDPAGE                319
#define IDR_JPGNEWPASSWORDFILE          320
#define IDR_JPGNEWPASSWORDASK           321
#define IDR_JPGPLAYERINFO               322
#define IDR_JPGACCOUNTEDIT              323
#define IDR_JPGLARGETTSPAGE             324
#define IDR_JPGLINKWORLD                326
#define IDR_JPG1                        327
#define IDR_JPGRELOGONPAGE              327
#define IDB_VERBEXIT                    328
#define IDR_WAVECOUGH                   329
#define IDR_WAVEWATERWAVE               330
#define IDR_WAVEWATERWAVE2              331
#define IDR_WAVEWATERWAVE3              332
#define IDR_WAVEFIRE3                   333
#define IDR_WAVEFIRE1                   334
#define IDR_WAVEFIRE2                   335
#define IDR_WAVEWHISTLINGKITE2          336
#define IDR_WAVEAVIARYBIRD1             337
#define IDR_WAVEAVIARYBIRD2             338
#define IDR_WAVEAVIARYBIRD3             339
#define IDR_WAVEAVIARYBIRD5             340
#define IDR_WAVEAVIARYBIRD6             341
#define IDR_WAVEAVIARYBIRD8             342
#define IDR_WAVEAVIARYBIRD9             343
#define IDR_WAVEREDTAILEDBLACKCOCKATOO1 344
#define IDR_WAVEWHISTLINGKITE1          345
#define IDR_WAVE1                       346
#define IDR_WAVEROWING2                 346
#define IDR_WAVECRICKETS1               347
#define IDR_WAVECRICKETS2               348
#define IDR_WAVECRICKETS3               349
#define IDR_WAVECURLEWSYOUNG7           350
#define IDR_WAVEROWING1                 351
#define IDR_WAVE2                       352
#define IDR_WAVEBEEPINFO                352
#define IDR_WAVE4                       353
#define IDR_WAVESWITCHCLICK1            353
#define IDR_JPG2                        354
#define IDR_JPGTEXTURE17                354
#define IDR_JPGTEXTURE1                 355
#define IDR_JPGTEXTURE2                 356
#define IDR_JPGTEXTURE3                 357
#define IDR_JPGTEXTURE4                 358
#define IDR_JPGTEXTURE5                 359
#define IDR_JPGTEXTURE6                 360
#define IDR_JPGTEXTURE7                 361
#define IDR_JPGTEXTURE8                 362
#define IDR_JPGTEXTURE9                 363
#define IDR_JPGTEXTURE10                364
#define IDR_JPGTEXTURE11                365
#define IDR_JPGTEXTURE12                366
#define IDR_JPGTEXTURE13                367
#define IDR_JPGTEXTURE14                368
#define IDR_JPGTEXTURE15                369
#define IDR_JPGTEXTURE16                370
#define IDR_MMLMACROS                   500
#define IDR_MMLTEMPLATEBACK             501
#define ID_ACCELERATORF1                40001
#define ID_ACCELERATORF2                40002
#define ID_ACCELERATORF3                40003
#define ID_ACCELERATORF4                40004
#define ID_ACCELERATOREDITFOCUS         40006
#define ID_ACCELERATORCHATFOCUS         40007
#define ID_TASKBAR_SHOWTITLE            40009

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        371
#define _APS_NEXT_COMMAND_VALUE         40010
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
